### ISSUE TITLE
VPN app and Voice Assistant

### ISSUE THREAD

**Issue by urbien** [tradle/simplecloud#2]
# Project plan for VPN app and Voice Assistant 

1. [ ] Build a mobile app, starting with WireGuardKit. There will be a need to create a React Native wrapper around it, but it does not need to be JSI, as this is just for configuration, not traffic and as such low performance of the current JS bridge is fine.
1. [ ] Build Alexa SDK clone. This needs only for a subset of functions that Alexa Skills built by our partners in Hospitality. Let's give it a working title VoicePal
1. [ ] Work with the AI developer to incorporate their components into VoicePal.
1. [ ] Work with QubesOS guys to make sure VoicePal run fine inside MicroVM that is launched on demand. This should not be too hard as VoicePal will run in a docker container.
1. [ ] Use Hypercore as a data layer in Alexa Skills for collecting all customer data and syncing it to mobile app.  VoicePal apps will save data into MultiHyperBee. Data will be like this: 
   - order room service (date / time, who ordered, what was ordered, prices)
   - reserve the SPA in the hotel
   - self-checkin data (ID, date/time, what room, etc,) and self-checkout (who, when, number of days stayed, services used, bill)
